version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - /Users/adarsh.manoharan/Assignments/conrad/docker-compose-nginx/html:/usr/share/nginx/html
      - /Users/adarsh.manoharan/Assignments/conrad/docker-compose-nginx/logs:/var/log/nginx
      - /Users/adarsh.manoharan/Assignments/conrad/docker-compose-nginx/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always